### ISSUE TITLE
Creation of new product & plan

### ISSUE THREAD

**Issue by lowlyocean** [adrienverge/localstripe#150]
Hello, thank you for developing this needful project. I'm running into errors below with sequence of requests shown (these work against real Stripe API). This is expected to create a product, and a plan for that product. Is there some configuration I need to do, or a debug flag I can enable for more detailed error message?

1. `curl 'http://localhost:8420/v1/products' -d name=SaaS -d id=prod_saas -u sk_test_12345:`
```
{
  "error": {
    "message": "Bad request",
    "type": "invalid_request_error"
  }
}
```

2. `curl http://localhost:8420/v1/plans -u sk_test_12345: -d amount=500 -d currency=usd -d interval=month -d product=prod_saas -d 'metadata[code]=paid'`
```
{
  "error": {
    "message": "Not Found",
    "type": "invalid_request_error"
  }
}
```

**Comment by adrienverge** [comment]
Hello,

You can see directly in the code a working example:
https://github.com/adrienverge/localstripe/blob/38add1cecbd447d777c7cedc803f79302113c1bb/test.sh#L143-L146
and the code that handles your request:
https://github.com/adrienverge/localstripe/blob/38add1cecbd447d777c7cedc803f79302113c1bb/localstripe/resources.py#L2022-L2055

I guess the `invalid_request_error` problem occurs because you don't pass a `type` parameter (`service`|`good`).
That's strange because:
- [the latest API documentation](https://stripe.com/docs/api/products/create) doesn't show this parameter (it has been removed?)
- it is mentioned in [the API docs for deleting a product](https://stripe.com/docs/api/products/delete),
- [other parts of the documentation](https://stripe.com/docs/billing/subscriptions/products-and-prices#products) mention it too,
- I don't find any info in [the official changelog](https://stripe.com/docs/upgrades).


Can you tell what Stripe API version you are using? What happens with the real Stripe servers if you don't pass the parameter? Does the returned object have a `type`?

**Comment by lowlyocean** [comment]
Ah yes, strange since the doc for product creation don't mention the type parameter. Looks like my Stripe API version is [2020-08-27](https://stripe.com/docs/upgrades#2020-08-27). The requests above (without type parameter) work just fine against real API. The response seems to return type as "service"

**Comment by adrienverge** [comment]
In this case, we could modify localstripe so it accepts requests without `type` and default to `type = 'service'`. Do you want to contribute?

**Comment by lowlyocean** [comment]
Happy to create pull request. I'm able to create the product & plan if I default type='service' but now I'm noticing that request below to list plans fails with connect ECONNREFUSED, has it been observed before?
`curl --location --request GET 'http://localhost:8240/v1/plans' --data-urlencode 'limit=3`

**Comment by lowlyocean** [comment]
Debugging a bit, also seems [this line](https://github.com/adrienverge/localstripe/blob/38add1cecbd447d777c7cedc803f79302113c1bb/localstripe/resources.py#L166) raises an exception if receiving a GET request to /v1/customers containing [email parameter](https://stripe.com/docs/api/customers/list#list_customers-email) e.g.
`stripe.Customer.list(email = 'address@domain.com')`
